## Travis File
language: python
python:
  - "3.6"

# run checks on Markdown writing through proselint script:
install:
  #proselint install:
  - sudo pip install proselint
  - pip install --upgrade pip
  - pip3 install pep8

script:
  # use proselint
  - proselint README.md
  - find . -name \*.py -exec pep8 --ignore=E402 {} +
